### ISSUE TITLE
【Web端、Android端】Web端使用TUICallEngine Version:1.0.4 拨打视频通话给两个移动端设备（使用TUIKit），其中一个先接听后直接挂断，整个会话中断触发callend事件

### ISSUE THREAD

**Issue by dicksonic** [tencentyun/TUICallKit#146]
SDKAPPID:1400744410
USERID:13372131676 呼叫 USERID：15632563252,13333322453
问题描述：Web端使用TUICallEngine Version:1.0.4 拨打视频通话给两个移动端设备（使用TUIKit），其中一个先接听后直接挂断，整个会话中断，触发了CallEnd事件
Web端使用的组件版本如下：
![image](https://user-images.githubusercontent.com/19483258/197719087-1e4ed9d4-15ad-48ff-ac28-5a10fae9d53f.png)
![image](https://user-images.githubusercontent.com/19483258/197719270-ce21af59-abb7-4502-b99b-bac4ba555c82.png)
移动端使用的TUIKIT版本如下：
![image](https://user-images.githubusercontent.com/19483258/197718268-5a61f027-a0a7-4f2d-9ad4-c0b92b0213d5.png)

**Comment by MinTate** [comment]
![8ea35635c3ea4d73ac505498d1ddd587](https://user-images.githubusercontent.com/16069375/197923407-3ea3567b-90c0-4a15-833a-6cf4ebdce2d8.png)
这里有点奇怪，主叫和被叫貌似都是Windows端的Web，并非Android 设备？

**Comment by dicksonic** [comment]
之前测试的时候还测试过被叫是pc端的，今天用了上述id重现了下（web端呼叫两个安卓手机端），麻烦看下

**Comment by reneechai** [comment]
> 之前测试的时候还测试过被叫是pc端的，今天用了上述id重现了下（web端呼叫两个安卓手机端），麻烦看下 ![image](https://user-images.githubusercontent.com/19483258/198173378-e1325a5d-1d52-4488-9fc8-40058b0cd90d.png)

该问题web端已修复，版本预计明天发布，具体请关注web发布公告，https://cloud.tencent.com/document/product/647/80930
感谢您的支持~

**Comment by rgzhaoh** [comment]
@dicksonic   TUICallEngine v1.1.0 已发布解决，请升级！https://www.npmjs.com/package/tuicall-engine-webrtc
