### ISSUE TITLE
[Flutter-iOS]: Error (Xcode): Framework not found TXFFmpeg

### ISSUE THREAD

**Issue by toonTheta** [tencentyun/TUICallKit#179]
Hello, I would like to say that this package is very interesting and I want to try this package to my Flutter project.
Now I tried to use the Flutter example provided in this project but I failed to built and get this error when I build for iOS simulator

<img width="1572" alt="Screen Shot 2566-01-03 at 12 13 23" src="https://user-images.githubusercontent.com/46107561/210303242-2460c573-cef7-4f8b-af3c-88184ff55146.png">

But Android is fine...

What should I do?

**Comment by toonTheta** [comment]
Oh I found that it is currently not support for iOS simulator

**Comment by MinTate** [comment]
Thanks，we will soon support debugging for the iOS Simulator~
