### ISSUE TITLE
uniapp vue3主包过大怎么解决

### ISSUE THREAD

**Issue by haliuhei** [tencentyun/TUICallKit#196]
[https://github.com/tencentyun/TUICallKit/tree/main/uni-app/TUICallKit-Miniprogram/TUICallKit-Vue3](https://github.com/tencentyun/TUICallKit/tree/main/uni-app/TUICallKit-Miniprogram/TUICallKit-Vue3)
如题，跑了一下demo.运行起来后上传的小程序包已经接近1.8M，其他业务都无法在主包中写了。
怎么解决主包过大的问题，或者能否提供一个此程序运行在分包的demo。
目前因为主包已经写了大概不到 1m的业务，想将音视频相关的页面分包处理。

**Comment by rgzhaoh** [comment]
代码中通过 import 引入的 tim-wx-sdk 改成：const TIM = require('tim-wx-sdk'); demo 已经更新，请参考最新的 demo
