### ISSUE TITLE
插件一直往这个域名发post请求https://aegis.qq.com/speed

### ISSUE THREAD

**Issue by zaxlct** [tencentyun/TUICallKit#219]
![image](https://user-images.githubusercontent.com/14342431/231370468-593b4752-f568-461b-ab64-1338722afb0b.png)
im 页面没打开，我打开的是我项目其他的页面，只要我其他的页面发起我自己的 ajax 请求，插件就自动往https://aegis.qq.com/speed发好几次请求，这样在干嘛？监控什么

**Comment by wbxl2000** [comment]
您好，非常感谢您的反馈。我们目前仅在 Demo 中进行了上报操作。如果您使用的是打包后的 CallKit 版本，您可以直接升级到最新版本，以解决此问题。如果您使用的是源码集成的版本，在代码中将 `logReport.` 注释掉即可。希望这些信息对您有所帮助！
<img width="379" alt="image" src="https://user-images.githubusercontent.com/57169560/231644184-3e46a026-d5ea-4631-84b5-467ec80cd36d.png">

**Comment by zaxlct** [comment]
@wbxl2000 
你好，我使用的是 "@tencentcloud/chat-uikit-vue@1.4.1"版本。这个版本应该是最新的。代码里找不到 `logReport.`。问题还是没解决，所以需要 @tencentcloud/chat-uikit-vue 发布新版本才能解决问题是吗

**Comment by Ashster** [comment]
您好，这是chat-uikit-vue中对于页面启动速度的性能监控统计，不会统计到您的具体内部业务逻辑，若您不需要性能上报，请将您源码接入的chat-uikit-vue中，utils/TUIAegis 文件中constructor内代码注释即可。
