### ISSUE TITLE
运行TUICallKit/Flutter/example，正常启动输入call userid后直接报下面的错误

### ISSUE THREAD

**Issue by camelus0211** [tencentyun/TUICallKit#232]
E/AndroidRuntime(17074): FATAL EXCEPTION: main
E/AndroidRuntime(17074): Process: com.tencent.cloud.tuikit.flutter.tuicall_kit_example, PID: 17074
E/AndroidRuntime(17074): android.view.InflateException: Binary XML file line #14 in com.tencent.cloud.tuikit.flutter.tuicall_kit_example:layout/tuicalling_group_user_layout: Binary XML file line #14 in com.tencent.cloud.tuikit.flutter.tuicall_kit_example:layout/tuicalling_group_user_layout: Error inflating class com.tencent.qcloud.tuicore.component.RoundCornerImageView
E/AndroidRuntime(17074): Caused by: android.view.InflateException: Binary XML file line #14 in com.tencent.cloud.tuikit.flutter.tuicall_kit_example:layout/tuicalling_group_user_layout: Error inflating class com.tencent.qcloud.tuicore.component.RoundCornerImageView
E/AndroidRuntime(17074): Caused by: java.lang.ClassNotFoundException: com.tencent.qcloud.tuicore.component.RoundCornerImageView
E/AndroidRuntime(17074):        at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(17074):        at java.lang.Class.forName(Class.java:454)
E/AndroidRuntime(17074):        at android.view.LayoutInflater.createView(LayoutInflater.java:819)
E/AndroidRuntime(17074):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/AndroidRuntime(17074):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/AndroidRuntime(17074):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/AndroidRuntime(17074):        at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
E/AndroidRuntime(17074):        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.base.UserLayout.initView(UserLayout.java:36)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.base.UserLayout.<init>(UserLayout.java:31)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.base.UserLayout.<init>(UserLayout.java:26)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.view.UserLayoutFactory.allocUserLayout(UserLayoutFactory.java:32)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.view.TUICallingViewManager.initSingleVideoWaitingView(TUICallingViewManager.java:343)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.view.TUICallingViewManager.initSingleWaitingView(TUICallingViewManager.java:307)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.view.TUICallingViewManager.createCallingView(TUICallingViewManager.java:109)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.TUICallKitImpl.showCallingView(TUICallKitImpl.java:253)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.TUICallKitImpl.access$300(TUICallKitImpl.java:44)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallkit.TUICallKitImpl$1$1.onSuccess(TUICallKitImpl.java:146)
E/AndroidRuntime(17074):        at com.tencent.qcloud.tuikit.tuicallengine.l.b$a.run(ICallback.java:3)
E/AndroidRuntime(17074):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(17074):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17074):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17074):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17074):        at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime(17074):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17074):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17074):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(17074): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qcloud.tuicore.component.RoundCornerImageView" on path: DexPathList[[zip file "/data/app/~~kTmWW9lCLfpc8pf6t1tCEQ==/com.tencent.cloud.tuikit.flutter.tuicall_kit_example-ZA9j6dzE6uU90IVXkttA6Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~kTmWW9lCLfpc8pf6t1tCEQ==/com.tencent.cloud.tuikit.flutter.tuicall_kit_example-ZA9j6dzE6uU90IVXkttA6Q==/lib/arm64, /data/app/~~kTmWW9lCLfpc8pf6t1tCEQ==/com.tencent.cloud.tuikit.flutter.tuicall_kit_example-ZA9j6dzE6uU90IVXkttA6Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(17074):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(17074):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(17074):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(17074):        ... 27 more
I/Process (17074): Sending signal. PID: 17074 SIG: 9
Lost connection to device.

**Comment by MinTate** [comment]
> E/AndroidRuntime(17074): FATAL EXCEPTION: main E/AndroidRuntime(17074): Process: com.tencent.cloud.tuikit.flutter.tuicall_kit_example, PID: 17074 E/AndroidRuntime(17074): android.view.InflateException: Binary XML file line #14 in com.tencent.cloud.tuikit.flutter.tuicall_kit_example:layout/tuicalling_group_user_layout: Binary XML file line #14 in com.tencent.cloud.tuikit.flutter.tuicall_kit_example:layout/tuicalling_group_user_layout: Error inflating class com.tencent.qcloud.tuicore.component.RoundCornerImageView E/AndroidRuntime(17074): Caused by: android.view.InflateException: Binary XML file line #14 in com.tencent.cloud.tuikit.flutter.tuicall_kit_example:layout/tuicalling_group_user_layout: Error inflating class com.tencent.qcloud.tuicore.component.RoundCornerImageView E/AndroidRuntime(17074): Caused by: java.lang.ClassNotFoundException: com.tencent.qcloud.tuicore.component.RoundCornerImageView E/AndroidRuntime(17074): at java.lang.Class.classForName(Native Method) E/AndroidRuntime(17074): at java.lang.Class.forName(Class.java:454) E/AndroidRuntime(17074): at android.view.LayoutInflater.createView(LayoutInflater.java:819) E/AndroidRuntime(17074): at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010) E/AndroidRuntime(17074): at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965) E/AndroidRuntime(17074): at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) E/AndroidRuntime(17074): at android.view.LayoutInflater.inflate(LayoutInflater.java:660) E/AndroidRuntime(17074): at android.view.LayoutInflater.inflate(LayoutInflater.java:538) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.base.UserLayout.initView(UserLayout.java:36) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.base.UserLayout.(UserLayout.java:31) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.base.UserLayout.(UserLayout.java:26) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.view.UserLayoutFactory.allocUserLayout(UserLayoutFactory.java:32) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.view.TUICallingViewManager.initSingleVideoWaitingView(TUICallingViewManager.java:343) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.view.TUICallingViewManager.initSingleWaitingView(TUICallingViewManager.java:307) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.view.TUICallingViewManager.createCallingView(TUICallingViewManager.java:109) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.TUICallKitImpl.showCallingView(TUICallKitImpl.java:253) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.TUICallKitImpl.access$300(TUICallKitImpl.java:44) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallkit.TUICallKitImpl$1$1.onSuccess(TUICallKitImpl.java:146) E/AndroidRuntime(17074): at com.tencent.qcloud.tuikit.tuicallengine.l.b$a.run(ICallback.java:3) E/AndroidRuntime(17074): at android.os.Handler.handleCallback(Handler.java:938) E/AndroidRuntime(17074): at android.os.Handler.dispatchMessage(Handler.java:99) E/AndroidRuntime(17074): at android.os.Looper.loopOnce(Looper.java:201) E/AndroidRuntime(17074): at android.os.Looper.loop(Looper.java:288) E/AndroidRuntime(17074): at android.app.ActivityThread.main(ActivityThread.java:7870) E/AndroidRuntime(17074): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(17074): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) E/AndroidRuntime(17074): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) E/AndroidRuntime(17074): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.qcloud.tuicore.component.RoundCornerImageView" on path: DexPathList[[zip file "/data/app/~~kTmWW9lCLfpc8pf6t1tCEQ==/com.tencent.cloud.tuikit.flutter.tuicall_kit_example-ZA9j6dzE6uU90IVXkttA6Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~kTmWW9lCLfpc8pf6t1tCEQ==/com.tencent.cloud.tuikit.flutter.tuicall_kit_example-ZA9j6dzE6uU90IVXkttA6Q==/lib/arm64, /data/app/~~kTmWW9lCLfpc8pf6t1tCEQ==/com.tencent.cloud.tuikit.flutter.tuicall_kit_example-ZA9j6dzE6uU90IVXkttA6Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] E/AndroidRuntime(17074): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218) E/AndroidRuntime(17074): at java.lang.ClassLoader.loadClass(ClassLoader.java:379) E/AndroidRuntime(17074): at java.lang.ClassLoader.loadClass(ClassLoader.java:312) E/AndroidRuntime(17074): ... 27 more I/Process (17074): Sending signal. PID: 17074 SIG: 9 Lost connection to device.

Hello，您好，这个问题我们新版本已经修复，可以更新一下仓库~
