### ISSUE TITLE
微信小程序视频通话时，若微信小程序用户中途切换到别的APP，会导致另一方无法收到微信小程序用户的视频影像和声音

### ISSUE THREAD

**Issue by LBruse** [tencentyun/TUICallKit#54]
sdkappid: 1400487238
userid: 13514114955
userid: 15768357131
发起通话时间： 2022-06-01 22:41:43
结束通话时间： 2022-06-01 22:55:49
SDK 版本：V9.6.1

业务场景：
通话发起方A在微信小程序上发起视频通话，通话接收方B在Android端接听视频通话。1对1的视频通话。

问题描述：
当A在微信小程序视频通话过程中，中途切换到别的APP或者返回到微信APP进行别的操作时，B会看不到A的视频，且听不到A的声音。同时A也看不到B的视频画面，且听不到B的声音。同时录制的视频，会提示“主播暂时离开，请稍等片刻...”。

请问视频通话过程中，一定要保证TUICalling始终运行在最前端吗？即如果视频通话中途切换到别的APP做一些别的事情，那么则会不可避免地产生如上所述问题？？

![image](https://user-images.githubusercontent.com/25904146/172088427-6650c6ce-ec07-483e-832e-56720010974f.png)

**Comment by MinTate** [comment]
Hello，确认了一下，这个是小程序隐私的限制，退到后台默认摄像头就无法采集，目前的我们会提供一个默认图片，即如图所示，如果想自定义图片话，可以通过下面的方式自行设置一下：

```
this.TRTC.setPusherAttributes({
	waitingImage: 'xxxx'
})

```
代码片段可参考 github 链接：https://github.com/tencentyun/TRTCSDK/blob/master/WXMini/TRTCSimpleDemo/pages/videocall/room/room.js
