### ISSUE TITLE
Android 集成了TUICalling组件。在我已和一个用户进行视频通话时，如何再次邀请多个用户进行通话？就像微信一样

### ISSUE THREAD

**Issue by zengxuewen94** [tencentyun/TUICallKit#55]
Android 集成了TUICalling组件。在我已和一个用户进行视频通话时，如何再次邀请多个用户进行通话？就像微信一样

**Comment by PualGeorge** [comment]
此功能正在开发中，预计月底会发布

**Comment by MinTate** [comment]
> 

Hello，通话过邀请用户的这个功能，在升级版的TUICallKit组件里面已经实现，可以看一下这个文档：https://cloud.tencent.com/document/product/647/78729
