### ISSUE TITLE
TUILogin新的login,logout接口，登录再退出，再登录后，无法接听来电

### ISSUE THREAD

**Issue by flysec** [tencentyun/TUICallKit#67]
MainActivity中，目前logout用的是
TUILogin.logout(new V2TIMCallback() {
但是这个接口Deprecated了

改为新接口
TUILogin.logout(new TUICallback() { 后，发现登录，再登出，再登录后，无法接听来电（来电页面弹不出来）
原因可能是新接口中，会调用到V2TIMManager.getInstance().unInitSDK();引起mSignalingListenerList.clear();丢失回调

**Comment by PualGeorge** [comment]
最新代码已经解决次问题，请拉取最新代码，感谢您的宝贵意见
