### ISSUE TITLE
 api "com.tencent.liteav:LiteAVSDK_TRTC:10.4.0.11163"

### ISSUE THREAD

**Issue by AlbertShen0211** [tencentyun/TUICallKit#72]
022-07-22 10:17:55.927 9911-9911/com.tencent.qcloud.tim.tuikit E/loud.tim.tuiki: No implementation found for void com.tencent.liteav.trtc.TrtcCloudJni.nativeGlobalInit(int) (tried Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit and Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit__I)
2022-07-22 10:17:55.927 9911-9911/com.tencent.qcloud.tim.tuikit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.qcloud.tim.tuikit, PID: 9911
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.trtc.TrtcCloudJni.nativeGlobalInit(int) (tried Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit and Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit__I)
        at com.tencent.liteav.trtc.TrtcCloudJni.nativeGlobalInit(Native Method)
        at com.tencent.liteav.trtc.TrtcCloudJni.init(SourceFile:930)
        at com.tencent.liteav.trtc.TRTCCloudImpl.b(SourceFile:46)
        at com.tencent.liteav.trtc.TRTCCloudImpl.<init>(SourceFile:112)
        at com.tencent.liteav.trtc.TRTCCloudImpl.a(SourceFile:76)
        at com.tencent.trtc.TRTCCloud.sharedInstance(SourceFile:43)
        at com.tencent.liteav.trtccalling.model.TRTCCalling.<init>(TRTCCalling.java:998)
        at com.tencent.liteav.trtccalling.model.TRTCCalling.sharedInstance(TRTCCalling.java:187)

**Comment by PualGeorge** [comment]
clear一下然后重新build

**Comment by MinTate** [comment]
> 022-07-22 10:17:55.927 9911-9911/com.tencent.qcloud.tim.tuikit E/loud.tim.tuiki: No implementation found for void com.tencent.liteav.trtc.TrtcCloudJni.nativeGlobalInit(int) (tried Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit and Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit__I) 2022-07-22 10:17:55.927 9911-9911/com.tencent.qcloud.tim.tuikit E/AndroidRuntime: FATAL EXCEPTION: main Process: com.tencent.qcloud.tim.tuikit, PID: 9911 java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.trtc.TrtcCloudJni.nativeGlobalInit(int) (tried Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit and Java_com_tencent_liteav_trtc_TrtcCloudJni_nativeGlobalInit__I) at com.tencent.liteav.trtc.TrtcCloudJni.nativeGlobalInit(Native Method) at com.tencent.liteav.trtc.TrtcCloudJni.init(SourceFile:930) at com.tencent.liteav.trtc.TRTCCloudImpl.b(SourceFile:46) at com.tencent.liteav.trtc.TRTCCloudImpl.(SourceFile:112) at com.tencent.liteav.trtc.TRTCCloudImpl.a(SourceFile:76) at com.tencent.trtc.TRTCCloud.sharedInstance(SourceFile:43) at com.tencent.liteav.trtccalling.model.TRTCCalling.(TRTCCalling.java:998) at com.tencent.liteav.trtccalling.model.TRTCCalling.sharedInstance(TRTCCalling.java:187)

Hello，这个问题我们已经更新到Android的常见问题里面：https://cloud.tencent.com/document/product/647/78767，Clean 一下就好了~
