### ISSUE TITLE
咨询将音频/视频通话内容录音/录像后存入腾讯云对象存储的实现方案。

### ISSUE THREAD

**Issue by Ma-Weijian** [tencentyun/TUICallKit#76]
您好。

腾讯云音视频通话组件为我们提供了非常方便的安卓和ios应用内通话/录音的一站式解决方案。由于业务需要将通话/视频留档，想咨询一下使用TUICalling组件，如何对通话/视频内容进行录音/录像，并在通话结束后将文件存储至腾讯云的对象存储。

希望能有比较简洁的解决方案。

非常感谢！

**Comment by PualGeorge** [comment]
目前TUICalling没有录制的功能，您可以可以参考一下录制的文档 https://cloud.tencent.com/document/product/647/16823自行实现

**Comment by MinTate** [comment]
> 您好。
> 
> 腾讯云音视频通话组件为我们提供了非常方便的安卓和ios应用内通话/录音的一站式解决方案。由于业务需要将通话/视频留档，想咨询一下使用TUICalling组件，如何对通话/视频内容进行录音/录像，并在通话结束后将文件存储至腾讯云的对象存储。
> 
> 希望能有比较简洁的解决方案。
> 
> 非常感谢！

Hello，TUICallKit/TUICalling 组件是底层依赖了腾讯云实时音视频（TRTC）,TRTC是提供有一站式的云端录制功能并存储到COS上的，TRTC 控制台开通就行，可以看一下这个文档：https://cloud.tencent.com/document/product/647/76497
